import { CapScheduleDB } from './db.js';

const db = new CapScheduleDB();
const $ = sel => document.querySelector(sel);
const $$ = sel => [...document.querySelectorAll(sel)];
const pad = n => String(n).padStart(2,'0');
const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const timeMinutes = t => { const [h,m]=String(t||'00:00').slice(0,5).split(':').map(Number); return h*60+m; };
const minutesTime = m => `${pad(Math.floor(m/60))}:${pad(m%60)}`;
const fmtTime = t => { if(!t)return''; const [h,m]=String(t).slice(0,5).split(':').map(Number); return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,h,m)); };
const fmtDate = d => new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(`${d}T12:00:00`));
const monthLabel = d => new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(d);
const sameMonth = (d,y,m) => d.getFullYear()===y && d.getMonth()+1===m;
const nthWeekday = (year,month,weekday,n) => {const d=new Date(year,month,1);d.setDate(1+((7+weekday-d.getDay())%7)+(n-1)*7);return d;};
const lastWeekday = (year,month,weekday) => {const d=new Date(year,month+1,0);d.setDate(d.getDate()-((7+d.getDay()-weekday)%7));return d;};
function easterDate(year){let a=year%19,b=Math.floor(year/100),c=year%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31)-1,day=((h+l-7*m+114)%31)+1;return new Date(year,month,day);}
function holidayLabel(iso){const d=new Date(`${iso}T12:00:00`),y=d.getFullYear(),m=d.getMonth(),day=d.getDate();const same=x=>x.getMonth()===m&&x.getDate()===day;const fixed={[0*100+1]:"New Year's Day",[1*100+14]:"Valentine's Day",[6*100+4]:"Independence Day",[9*100+31]:"Halloween",[10*100+11]:"Veterans Day",[11*100+25]:"Christmas Day"};const key=m*100+day;if(fixed[key])return fixed[key];if(same(nthWeekday(y,0,1,3)))return'Martin Luther King Jr. Day';if(same(nthWeekday(y,1,1,3)))return'Presidents Day';if(same(easterDate(y)))return'Easter Sunday';if(same(nthWeekday(y,4,0,2)))return"Mother's Day";if(same(lastWeekday(y,4,1)))return'Memorial Day';if(same(nthWeekday(y,5,0,3)))return"Father's Day";if(same(nthWeekday(y,8,1,1)))return'Labor Day';if(same(nthWeekday(y,9,1,2)))return'Columbus Day / Indigenous Peoples’ Day';if(same(nthWeekday(y,10,4,4)))return'Thanksgiving Day';return'';}

const state = {
  units:[], user:null, publicDate:new Date(), planDate:new Date(),
  publicLookup:null, planLookup:null, planning:null, selectedMeetingId:null,
  meetingDialogMode:'add', copySourceMeetingId:null, activeAdminPage:'units'
};
state.publicDate = new Date(state.publicDate.getFullYear(),state.publicDate.getMonth(),1);
state.planDate = new Date(state.planDate.getFullYear(),state.planDate.getMonth(),1);

function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toastContainer').appendChild(el);setTimeout(()=>el.remove(),3800);}
function setBusy(el,busy,label){if(!el)return;if(busy){el.dataset.oldText=el.textContent;el.disabled=true;el.textContent=label||'Working…';}else{el.disabled=false;el.textContent=el.dataset.oldText||el.textContent;}}
function unitName(id){return state.units.find(u=>u.id===id)?.name||'Unknown Unit';}
function canEditAny(){return Boolean(state.user&&(state.user.isAppAdmin||state.user.permissions?.some(p=>p.can_edit_cadet||p.can_edit_senior)));}
function isAdminAny(){return Boolean(state.user&&(state.user.isAppAdmin||state.user.permissions?.some(p=>p.is_unit_admin)));}
function editableUnits(program=null){if(!state.user)return[];if(state.user.isAppAdmin)return state.units;return state.units.filter(u=>state.user.permissions?.some(p=>p.unit_id===u.id && (program?program==='cadet'?p.can_edit_cadet:p.can_edit_senior:(p.can_edit_cadet||p.can_edit_senior))));}
function adminUnits(){if(!state.user)return[];if(state.user.isAppAdmin)return state.units;return state.units.filter(u=>state.user.permissions?.some(p=>p.unit_id===u.id&&p.is_unit_admin));}

async function init(){
  bindGlobalUI();
  const initResult=await db.init(async ctx=>{state.user=ctx;await refreshAuthUI();});
  state.user=initResult.userContext;
  $('#modeBadge').textContent=initResult.demoMode?'Demo Mode':'Live Supabase';
  $('#modeBadge').className=`badge ${initResult.demoMode?'warning':'success'}`;
  state.units=await db.getUnits();
  populateUnitSelectors();
  restoreDeviceDefault();
  await refreshAuthUI();
  await renderPublicSchedule();
  await renderSpecialActivities();
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
}

function bindGlobalUI(){
  $$('.tab').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));
  $$('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog')?.close()));
  $('#loginButton').addEventListener('click',()=>$('#loginDialog').showModal());
  $('#accountButton').addEventListener('click',()=>{$('#accountPassword').value='';$('#accountPasswordConfirm').value='';$('#accountError').textContent='';$('#accountDialog').showModal();});
  $('#accountForm').addEventListener('submit',handleAccountPassword);
  $('#logoutButton').addEventListener('click',async()=>{await db.signOut();state.user=null;await refreshAuthUI();activateTab('schedule');toast('Logged out.');});
  $('#loginForm').addEventListener('submit',handleLogin);
  $('#publicUnitSelect').addEventListener('change',async()=>{syncDefaultCheckbox();await renderPublicSchedule();});
  $('#publicProgramSelect').addEventListener('change',async()=>{syncDefaultCheckbox();await renderPublicSchedule();});
  $('#saveDefaultSchedule').addEventListener('change',saveDeviceDefault);
  $('#printScheduleButton').addEventListener('click',()=>window.print());
  $('#publicPrevMonth').addEventListener('click',()=>shiftMonth('public',-1));
  $('#publicNextMonth').addEventListener('click',()=>shiftMonth('public',1));
  $('#publicCurrentMonth').addEventListener('click',()=>{state.publicDate=new Date(new Date().getFullYear(),new Date().getMonth(),1);updateMonthButtons();renderPublicSchedule();});
  $('#planPrevMonth').addEventListener('click',()=>shiftMonth('plan',-1));
  $('#planNextMonth').addEventListener('click',()=>shiftMonth('plan',1));
  $('#planCurrentMonth').addEventListener('click',()=>{state.planDate=new Date(new Date().getFullYear(),new Date().getMonth(),1);updateMonthButtons();loadPlanningMonth();});
  $('#planUnitSelect').addEventListener('change',loadPlanningMonth);
  $('#planProgramSelect').addEventListener('change',()=>{populatePlanUnitSelector();loadPlanningMonth();});
  $('#generateMeetingsButton').addEventListener('click',generateMeetings);
  $('#publishButton').addEventListener('click',publishSchedule);
  $('#addMeetingButton').addEventListener('click',()=>openMeetingDialog('add'));
  $('#meetingForm').addEventListener('submit',saveMeetingDialog);
  $('#meetingThemeSelect').addEventListener('change',saveMeetingHeader);
  $('#meetingUniformSelect').addEventListener('change',saveMeetingHeader);
  $('#meetingStartTime').addEventListener('change',saveMeetingHeader);
  $('#meetingEndTime').addEventListener('change',saveMeetingHeader);
  $('#cancelMeetingButton').addEventListener('click',toggleMeetingCancelled);
  $('#copyMeetingButton').addEventListener('click',()=>openMeetingDialog('copy'));
  $('#copyMonthButton').addEventListener('click',()=>{const source=new Date(state.planDate);source.setMonth(source.getMonth()-1);$('#copySourceMonth').value=`${source.getFullYear()}-${pad(source.getMonth()+1)}`;$('#copyMonthDialog').showModal();});
  $('#copyMonthForm').addEventListener('submit',copyMonth);
  $('#addEventButton').addEventListener('click',()=>openEventDialog());
  $('#eventForm').addEventListener('submit',saveEventForm);
  $('#deleteEventButton').addEventListener('click',deleteEvent);
  $('#activityLibraryButton').addEventListener('click',openActivityLibrary);
  $('#meetingTemplatesButton').addEventListener('click',openMeetingTemplates);
  $('#saveTemplateButton').addEventListener('click',saveCurrentMeetingTemplate);
  $('#activityUnitFilter').addEventListener('change',renderSpecialActivities);
  $('#activityRangeFilter').addEventListener('change',renderSpecialActivities);
  $('#addSpecialActivityButton').addEventListener('click',openSpecialActivityDialog);
  $('#specialActivityForm').addEventListener('submit',saveSpecialActivity);
  $$('.admin-nav-item').forEach(b=>b.addEventListener('click',()=>activateAdminPage(b.dataset.adminPage)));
}

function activateTab(name){
  $$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));
  $$('.tab-panel').forEach(x=>x.classList.remove('active'));
  $(`#${name}Tab`)?.classList.add('active');
  if(name==='planning') loadPlanningMonth();
  if(name==='activities') renderSpecialActivities();
  if(name==='admin') renderAdmin();
}

async function handleLogin(e){
  e.preventDefault();$('#loginError').textContent='';const button=e.submitter;setBusy(button,true,'Logging in…');
  try{state.user=await db.signIn($('#loginEmail').value,$('#loginPassword').value);$('#loginDialog').close();await refreshAuthUI();toast('Editor access enabled.','success');}
  catch(err){$('#loginError').textContent=err.message||String(err);}
  finally{setBusy(button,false);}
}

async function handleAccountPassword(e){e.preventDefault();const p=$('#accountPassword').value,c=$('#accountPasswordConfirm').value;$('#accountError').textContent='';if(p.length<8){$('#accountError').textContent='Use at least 8 characters.';return;}if(p!==c){$('#accountError').textContent='Passwords do not match.';return;}const b=e.submitter;setBusy(b,true,'Saving…');try{await db.updatePassword(p);$('#accountDialog').close();toast('Password updated.','success');}catch(err){$('#accountError').textContent=err.message||String(err);}finally{setBusy(b,false);}}

async function refreshAuthUI(){
  const logged=Boolean(state.user);$('#loginButton').classList.toggle('hidden',logged);$('#accountButton').classList.toggle('hidden',!logged);$('#logoutButton').classList.toggle('hidden',!logged);$('#userLabel').textContent=logged?(state.user.displayName||state.user.email):'';
  $('#planningTabButton').classList.toggle('hidden',!canEditAny());$('#adminTabButton').classList.toggle('hidden',!isAdminAny());$('#addSpecialActivityButton').classList.toggle('hidden',!canEditAny());
  $$('.app-admin-only').forEach(x=>x.classList.toggle('hidden',!state.user?.isAppAdmin));
  populatePlanUnitSelector();populateSpecialUnitSelector();
}

function populateUnitSelectors(){
  const opts=state.units.map(u=>`<option value="${u.id}">${esc(u.charter_number?`${u.charter_number} — `:'')}${esc(u.name)}</option>`).join('');
  $('#publicUnitSelect').innerHTML=opts;
  $('#activityUnitFilter').innerHTML=`<option value="all">All Units Statewide</option>${opts}`;
  populatePlanUnitSelector();populateSpecialUnitSelector();updateMonthButtons();
}
function populatePlanUnitSelector(){
  const program=$('#planProgramSelect')?.value||'cadet';const units=editableUnits(program);const old=$('#planUnitSelect')?.value;$('#planUnitSelect').innerHTML=units.map(u=>`<option value="${u.id}">${esc(u.charter_number?`${u.charter_number} — `:'')}${esc(u.name)}</option>`).join('');if(units.some(u=>u.id===old))$('#planUnitSelect').value=old;
}
function populateSpecialUnitSelector(){const units=editableUnits();$('#specialUnit').innerHTML=units.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('');}
function updateMonthButtons(){$('#publicCurrentMonth').textContent=monthLabel(state.publicDate);$('#planCurrentMonth').textContent=monthLabel(state.planDate);}
function shiftMonth(which,delta){const key=which==='public'?'publicDate':'planDate';state[key]=new Date(state[key].getFullYear(),state[key].getMonth()+delta,1);updateMonthButtons();if(which==='public')renderPublicSchedule();else loadPlanningMonth();}

function restoreDeviceDefault(){const pref=JSON.parse(localStorage.getItem('capSchedule.defaultSchedule')||'null');if(pref&&state.units.some(u=>u.id===pref.unitId)){$('#publicUnitSelect').value=pref.unitId;$('#publicProgramSelect').value=pref.program||'combined';}syncDefaultCheckbox();}
function saveDeviceDefault(){if($('#saveDefaultSchedule').checked){localStorage.setItem('capSchedule.defaultSchedule',JSON.stringify({unitId:$('#publicUnitSelect').value,program:$('#publicProgramSelect').value}));toast('Default schedule saved on this device.','success');}else{localStorage.removeItem('capSchedule.defaultSchedule');toast('Device default removed.');}}
function syncDefaultCheckbox(){const pref=JSON.parse(localStorage.getItem('capSchedule.defaultSchedule')||'null');$('#saveDefaultSchedule').checked=Boolean(pref&&pref.unitId===$('#publicUnitSelect').value&&pref.program===$('#publicProgramSelect').value);}

async function renderPublicSchedule(){
  const unitId=$('#publicUnitSelect').value;if(!unitId)return;const y=state.publicDate.getFullYear(),m=state.publicDate.getMonth()+1,program=$('#publicProgramSelect').value;$('#scheduleStatus').textContent='Loading published schedule…';
  try{state.publicLookup=await db.getLookupData(unitId);const rows=await db.getPublicMonth(unitId,y,m,program);$('#scheduleStatus').textContent=`${unitName(unitId)} • ${monthLabel(state.publicDate)} • Published schedules`;
    if(!rows.length){$('#publicSchedule').innerHTML=`<div class="empty-state"><h2>No published schedule</h2><p>There is no published ${program==='combined'?'cadet or senior':program} schedule for ${monthLabel(state.publicDate)}.</p></div>`;return;}
    $('#publicSchedule').innerHTML=rows.map(publicMeetingCard).join('');
  }catch(err){$('#scheduleStatus').textContent='';$('#publicSchedule').innerHTML=`<div class="empty-state"><h2>Unable to load schedule</h2><p>${esc(err.message)}</p></div>`;}
}
function publicMeetingCard(m){
  const d=new Date(`${m.meeting_date}T12:00:00`),theme=lookupName(state.publicLookup.themes,m.theme_id),uniform=lookupName(state.publicLookup.uniforms,m.uniform_id);const events=[...(m.events||[])].sort((a,b)=>String(a.start_time).localeCompare(String(b.start_time)));
  return `<article class="meeting-card ${m.is_cancelled?'cancelled':''}"><div class="meeting-card-header"><div class="date-box"><div class="dow">${d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()}</div><div class="day">${d.getDate()}</div></div><div class="meeting-title"><h2>${esc(m.title||theme||'Weekly Meeting')}</h2><div class="meeting-meta"><span class="program-pill ${m.program_type==='senior'?'senior':''}">${m.program_type==='senior'?'Senior':'Cadet'}</span><span>${esc(fmtTime(m.start_time))}–${esc(fmtTime(m.end_time))}</span>${uniform?`<span>UOD: ${esc(uniform)}</span>`:''}${m.is_cancelled?`<span class="badge danger">Cancelled</span>`:''}</div></div></div>${m.is_cancelled?`<div style="padding:16px;color:#8d1e27;font-weight:700">${esc(m.cancel_reason||'No meeting')}</div>`:`<table class="event-table"><thead><tr><th>Time</th><th>Activity</th><th>Room</th><th>Audience / Instructor</th><th>Category</th></tr></thead><tbody>${events.length?events.map(e=>`<tr><td class="event-time">${esc(fmtTime(e.start_time))}–${esc(fmtTime(e.end_time))}</td><td><strong>${esc(e.title)}</strong>${e.uniform_override_id?`<div class="muted-text">UOD: ${esc(lookupName(state.publicLookup.uniforms,e.uniform_override_id))}</div>`:''}</td><td>${esc(lookupName(state.publicLookup.rooms,e.room_id)||'General')}</td><td>${esc(e.audience||'')} ${e.instructor_name?`<div class="muted-text">${esc(e.instructor_name)}</div>`:''}</td><td><span class="event-category">${esc(lookupName(state.publicLookup.categories,e.category_id)||'Other')}</span></td></tr>`).join(''):`<tr><td colspan="5" class="muted-text">No activities have been published for this meeting.</td></tr>`}</tbody></table>`}</article>`;
}
function lookupName(list,id){return list?.find(x=>x.id===id)?.name||list?.find(x=>x.id===id)?.title||'';}

async function loadPlanningMonth(){
  if(!canEditAny())return;const unitId=$('#planUnitSelect').value,program=$('#planProgramSelect').value;if(!unitId||!db.canEdit(unitId,program)){state.planning=null;return;}
  $('#plannerSaveStatus').textContent='Loading draft…';
  try{const [planning,lookup]=await Promise.all([db.getPlanningMonth(unitId,program,state.planDate.getFullYear(),state.planDate.getMonth()+1),db.getLookupData(unitId)]);state.planning=planning;state.planLookup=lookup;const meetings=planning.version.meetings||[];state.selectedMeetingId=meetings.some(m=>m.id===state.selectedMeetingId)?state.selectedMeetingId:meetings[0]?.id||null;renderPlanning();$('#plannerSaveStatus').textContent='';}
  catch(err){$('#plannerSaveStatus').textContent=err.message;toast(err.message,'error');}
}
function renderPlanning(){if(!state.planning)return;const v=state.planning.version;$('#draftStatusLabel').textContent=v.status==='draft'?'Draft Schedule':v.status;$('#draftVersionLabel').textContent=` • Version ${v.version_number||1}`;renderMeetingList();renderRequirementDashboard();renderSelectedMeeting();}
function renderMeetingList(){const meetings=[...(state.planning?.version.meetings||[])].sort((a,b)=>a.meeting_date.localeCompare(b.meeting_date));$('#meetingList').innerHTML=meetings.length?meetings.map(m=>`<button class="meeting-list-item ${m.id===state.selectedMeetingId?'active':''}" data-meeting-id="${m.id}"><span class="meeting-list-dot ${m.is_cancelled?'cancelled':''}"></span><span><div class="meeting-list-date">${esc(new Date(`${m.meeting_date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}))}</div><div class="meeting-list-theme">${esc(m.is_cancelled?'Cancelled':`${holidayLabel(m.meeting_date)?`⚠ ${holidayLabel(m.meeting_date)} • `:''}${lookupName(state.planLookup?.themes,m.theme_id)||'Unassigned'}`)}</div></span></button>`).join(''):`<div class="muted-text" style="padding:12px">No meetings yet.</div>`;$$('.meeting-list-item').forEach(b=>b.addEventListener('click',()=>{state.selectedMeetingId=b.dataset.meetingId;renderPlanning();}));}
function selectedMeeting(){return state.planning?.version.meetings?.find(m=>m.id===state.selectedMeetingId)||null;}
function renderSelectedMeeting(){const m=selectedMeeting();$('#plannerEmpty').classList.toggle('hidden',Boolean(m));$('#plannerWorkspace').classList.toggle('hidden',!m);$('#meetingEditorHeader').classList.toggle('hidden',!m);if(!m)return;
  fillSelect($('#meetingThemeSelect'),state.planLookup.themes,m.theme_id,'— Select theme —');fillSelect($('#meetingUniformSelect'),state.planLookup.uniforms,m.uniform_id,'— Select UOD —');$('#meetingStartTime').value=String(m.start_time||'18:30').slice(0,5);$('#meetingEndTime').value=String(m.end_time||'21:00').slice(0,5);$('#cancelMeetingButton').textContent=m.is_cancelled?'Restore Meeting':'Cancel Meeting';renderPlannerBoard(m);}
function fillSelect(el,items,value,emptyLabel){el.innerHTML=(emptyLabel?`<option value="">${esc(emptyLabel)}</option>`:'')+(items||[]).map(x=>`<option value="${x.id}">${esc(x.name||x.title)}</option>`).join('');el.value=value||'';}

function renderRequirementDashboard(){
  const program=state.planning?.schedule.program_type;if(program!=='cadet'){const warnings=detectPlannerConflicts();$('#requirementDashboard').innerHTML=`<div class="requirement-card ${warnings.length?'short':'met'}"><div class="req-name">Validation</div><div class="req-value">${warnings.length?`${warnings.length} warning${warnings.length===1?'':'s'}`:'No conflicts'}</div><div class="req-sub">${esc(warnings[0]||'Rooms and instructors look clear')}</div></div><div class="muted-text" style="padding:8px">Cadet monthly content requirements are not applied to the senior schedule.</div>`;return;}
  const events=(state.planning.version.meetings||[]).filter(m=>!m.is_cancelled).flatMap(m=>m.events||[]);const requirements=(state.planLookup.requirements||[]).filter(r=>r.program_type==='cadet');
  const reqHtml=requirements.map(r=>{const matching=events.filter(e=>e.category_id===r.category_id);const minutes=matching.reduce((sum,e)=>sum+Math.max(0,timeMinutes(e.end_time)-timeMinutes(e.start_time)),0);let met,main,sub;if(r.occurrence_required){met=matching.length>0;main=met?'Scheduled':'Needed';sub=`${matching.length} occurrence${matching.length===1?'':'s'}`;}else{met=minutes>=Number(r.minimum_minutes||0);main=`${formatDuration(minutes)} / ${formatDuration(r.minimum_minutes||0)}`;sub=met?'Requirement met':`${formatDuration((r.minimum_minutes||0)-minutes)} remaining`;}return `<div class="requirement-card ${met?'met':'short'}"><div class="req-name">${esc(r.name)}</div><div class="req-value">${esc(main)}</div><div class="req-sub">${esc(sub)}</div></div>`;}).join('');
  const warnings=detectPlannerConflicts();const warningHtml=warnings.length?`<div class="requirement-card short" title="${esc(warnings.join(' | '))}"><div class="req-name">Validation</div><div class="req-value">${warnings.length} warning${warnings.length===1?'':'s'}</div><div class="req-sub">${esc(warnings[0])}${warnings.length>1?' …':''}</div></div>`:`<div class="requirement-card met"><div class="req-name">Validation</div><div class="req-value">No conflicts</div><div class="req-sub">Rooms and instructors look clear</div></div>`;
  $('#requirementDashboard').innerHTML=reqHtml+warningHtml;
}
function detectPlannerConflicts(){const warnings=[];for(const m of state.planning?.version.meetings||[]){if(m.is_cancelled)continue;const ev=[...(m.events||[])];for(let i=0;i<ev.length;i++)for(let j=i+1;j<ev.length;j++){const a=ev[i],b=ev[j],overlap=timeMinutes(a.start_time)<timeMinutes(b.end_time)&&timeMinutes(b.start_time)<timeMinutes(a.end_time);if(!overlap)continue;if(a.room_id&&b.room_id&&a.room_id===b.room_id)warnings.push(`${fmtDate(m.meeting_date)}: ${lookupName(state.planLookup.rooms,a.room_id)} has overlapping activities.`);if(a.instructor_name&&b.instructor_name&&a.instructor_name.trim().toLowerCase()===b.instructor_name.trim().toLowerCase())warnings.push(`${fmtDate(m.meeting_date)}: ${a.instructor_name} is assigned to overlapping activities.`);}}return [...new Set(warnings)];}
function formatDuration(min){min=Math.max(0,Number(min)||0);return `${Math.floor(min/60)}:${pad(min%60)}`;}

function renderPlannerBoard(meeting){
  const rooms=[{id:'',name:'General / Shared'},...(state.planLookup.rooms||[])];const start=timeMinutes(meeting.start_time||'18:30'),end=Math.max(start+30,timeMinutes(meeting.end_time||'21:00'));const total=end-start;const hourHeight=72,height=Math.max(360,total/60*hourHeight);const quarter=hourHeight/4;
  const board=$('#plannerBoard');board.innerHTML='';const grid=document.createElement('div');grid.className='planner-grid';grid.style.setProperty('--room-count',rooms.length);grid.style.setProperty('--planner-height',`${height}px`);grid.style.setProperty('--hour-height',`${hourHeight}px`);grid.style.setProperty('--quarter-height',`${quarter}px`);
  grid.appendChild(Object.assign(document.createElement('div'),{className:'planner-corner'}));rooms.forEach(r=>{const h=document.createElement('div');h.className='room-header';h.textContent=r.name;grid.appendChild(h);});
  const axis=document.createElement('div');axis.className='time-axis';for(let min=start;min<=end;min+=30){const l=document.createElement('div');l.className='time-label';l.style.top=`${(min-start)/60*hourHeight}px`;l.textContent=fmtTime(minutesTime(min));axis.appendChild(l);}grid.appendChild(axis);
  rooms.forEach(r=>{const lane=document.createElement('div');lane.className='room-lane';lane.dataset.roomId=r.id;grid.appendChild(lane);});board.appendChild(grid);
  (meeting.events||[]).forEach(event=>{const lane=grid.querySelector(`.room-lane[data-room-id="${CSS.escape(event.room_id||'')}"]`)||grid.querySelector('.room-lane');lane.appendChild(createEventBlock(event,start,end,hourHeight));});
}
function createEventBlock(event,start,end,hourHeight){const s=Math.max(start,timeMinutes(event.start_time)),e=Math.min(end,timeMinutes(event.end_time));const el=document.createElement('div');el.className='event-block';el.dataset.eventId=event.id;el.style.top=`${(s-start)/60*hourHeight}px`;el.style.height=`${Math.max(24,(e-s)/60*hourHeight)}px`;el.innerHTML=`<div class="event-block-title">${esc(event.title)}</div><div class="event-block-meta">${esc(fmtTime(event.start_time))}–${esc(fmtTime(event.end_time))}${event.instructor_name?` • ${esc(event.instructor_name)}`:''}</div><div class="resize-handle"></div>`;el.addEventListener('dblclick',()=>openEventDialog(event));el.addEventListener('pointerdown',startEventPointer);return el;}
function startEventPointer(e){if(e.button!==0)return;const block=e.currentTarget,event=findEvent(block.dataset.eventId),meeting=selectedMeeting();if(!event||!meeting)return;e.preventDefault();const resizing=e.target.classList.contains('resize-handle');const startY=e.clientY,origStart=timeMinutes(event.start_time),origEnd=timeMinutes(event.end_time),duration=origEnd-origStart;const mStart=timeMinutes(meeting.start_time),mEnd=timeMinutes(meeting.end_time);block.classList.add('dragging');block.setPointerCapture(e.pointerId);
  const move=ev=>{const pxPerMin=72/60,delta=Math.round(((ev.clientY-startY)/pxPerMin)/5)*5;if(resizing){const newEnd=Math.min(mEnd,Math.max(origStart+5,origEnd+delta));block.style.height=`${Math.max(24,(newEnd-origStart)*pxPerMin)}px`;block.dataset.previewEnd=minutesTime(newEnd);}else{let ns=Math.max(mStart,Math.min(mEnd-duration,origStart+delta));block.style.top=`${(ns-mStart)*pxPerMin}px`;block.dataset.previewStart=minutesTime(ns);block.dataset.previewEnd=minutesTime(ns+duration);const lane=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.room-lane');if(lane)block.dataset.previewRoom=lane.dataset.roomId;}};
  const up=async ev=>{block.removeEventListener('pointermove',move);block.removeEventListener('pointerup',up);block.classList.remove('dragging');const patch={...event,start_time:block.dataset.previewStart||event.start_time,end_time:block.dataset.previewEnd||event.end_time,room_id:block.dataset.previewRoom!==undefined?block.dataset.previewRoom:event.room_id};delete block.dataset.previewStart;delete block.dataset.previewEnd;delete block.dataset.previewRoom;try{setPlannerSaving(true);const saved=await db.saveEvent(meeting.id,patch);Object.assign(event,saved);setPlannerSaving(false,'Saved');renderPlanning();}catch(err){setPlannerSaving(false);toast(err.message,'error');renderPlanning();}};
  block.addEventListener('pointermove',move);block.addEventListener('pointerup',up);
}
function findEvent(id){for(const m of state.planning?.version.meetings||[]){const e=(m.events||[]).find(x=>x.id===id);if(e)return e;}return null;}
function setPlannerSaving(b,text=''){const el=$('#plannerSaveStatus');el.textContent=b?'Saving…':text;if(!b&&text)setTimeout(()=>{if(el.textContent===text)el.textContent='';},1600);}

async function generateMeetings(){if(!state.planning)return;const b=$('#generateMeetingsButton');setBusy(b,true);try{state.planning.version=await db.generateNormalMeetings(state.planning.version.id);state.selectedMeetingId=state.selectedMeetingId||state.planning.version.meetings?.[0]?.id;renderPlanning();toast('Normal weekly meetings generated.','success');}catch(err){toast(err.message,'error');}finally{setBusy(b,false);}}
function openMeetingDialog(mode){state.meetingDialogMode=mode;const d=$('#meetingDialog');d.querySelector('h2').textContent=mode==='copy'?'Copy Meeting to Date':'Add Meeting';const m=selectedMeeting();let target=new Date(state.planDate.getFullYear(),state.planDate.getMonth(),1);if(mode==='copy'&&m){target=new Date(`${m.meeting_date}T12:00:00`);target.setDate(target.getDate()+7);state.copySourceMeetingId=m.id;}$('#newMeetingDate').value=`${target.getFullYear()}-${pad(target.getMonth()+1)}-${pad(target.getDate())}`;d.showModal();}
async function saveMeetingDialog(e){e.preventDefault();const date=$('#newMeetingDate').value;if(!date)return;try{let m;if(state.meetingDialogMode==='copy')m=await db.copyMeeting(state.copySourceMeetingId,date);else m=await db.addMeeting(state.planning.version.id,date);state.planning.version.meetings.push?.(m);await reloadPlanningPreserve(m.id);$('#meetingDialog').close();toast(state.meetingDialogMode==='copy'?'Meeting copied.':'Meeting added.','success');}catch(err){toast(err.message,'error');}}
async function saveMeetingHeader(){const m=selectedMeeting();if(!m)return;const patch={theme_id:$('#meetingThemeSelect').value||null,uniform_id:$('#meetingUniformSelect').value||null,start_time:$('#meetingStartTime').value,end_time:$('#meetingEndTime').value};try{setPlannerSaving(true);const saved=await db.updateMeeting(m.id,patch);Object.assign(m,saved);setPlannerSaving(false,'Saved');renderPlanning();}catch(err){setPlannerSaving(false);toast(err.message,'error');}}
async function toggleMeetingCancelled(){const m=selectedMeeting();if(!m)return;try{const saved=await db.updateMeeting(m.id,{is_cancelled:!m.is_cancelled,cancel_reason:!m.is_cancelled?'No meeting':null});Object.assign(m,saved);renderPlanning();}catch(err){toast(err.message,'error');}}
async function copyMonth(e){e.preventDefault();const value=$('#copySourceMonth').value;if(!value)return;const [y,m]=value.split('-').map(Number);try{state.planning.version=await db.copyMonth(state.planning.version.id,y,m);state.selectedMeetingId=state.planning.version.meetings?.[0]?.id||null;$('#copyMonthDialog').close();renderPlanning();toast('Month copied into the current draft.','success');}catch(err){toast(err.message,'error');}}
async function publishSchedule(){if(!state.planning)return;if(!confirm(`Publish ${monthLabel(state.planDate)} for ${unitName(state.planning.schedule.unit_id)}? The current published version will be retained in history.`))return;const b=$('#publishButton');setBusy(b,true,'Publishing…');try{await db.publishVersion(state.planning.version.id);toast('Schedule published.','success');await renderPublicSchedule();await loadPlanningMonth();}catch(err){toast(err.message,'error');}finally{setBusy(b,false);}}
async function reloadPlanningPreserve(id){await loadPlanningMonth();if(id){state.selectedMeetingId=id;renderPlanning();}}

function openEventDialog(event=null,template=null){const m=selectedMeeting();if(!m)return;const data=event||{};$('#eventDialogTitle').textContent=event?'Edit Activity':'Schedule Activity';$('#eventId').value=data.id||'';$('#eventTitle').value=template?.title||data.title||'';$('#eventStart').value=String(data.start_time||m.start_time||'18:30').slice(0,5);const start=timeMinutes($('#eventStart').value),duration=template?.default_duration_minutes||30;$('#eventEnd').value=String(data.end_time||minutesTime(Math.min(timeMinutes(m.end_time),start+duration))).slice(0,5);fillSelect($('#eventRoom'),[{id:'',name:'General / Shared'},...(state.planLookup.rooms||[])],data.room_id||'');fillSelect($('#eventCategory'),state.planLookup.categories,template?.category_id||data.category_id,'— Other —');$('#eventAudience').value=template?.default_audience||data.audience||'';$('#eventInstructor').value=data.instructor_name||'';fillSelect($('#eventUniform'),state.planLookup.uniforms,data.uniform_override_id,'— Meeting default —');$('#eventDescription').value=data.description||'';$('#deleteEventButton').classList.toggle('hidden',!event);$('#eventDialog').showModal();}
async function saveEventForm(e){e.preventDefault();const meeting=selectedMeeting();const id=$('#eventId').value||null;const event={id,title:$('#eventTitle').value.trim(),start_time:$('#eventStart').value,end_time:$('#eventEnd').value,room_id:$('#eventRoom').value||null,category_id:$('#eventCategory').value||null,audience:$('#eventAudience').value.trim(),instructor_name:$('#eventInstructor').value.trim(),uniform_override_id:$('#eventUniform').value||null,description:$('#eventDescription').value.trim()};if(timeMinutes(event.end_time)<=timeMinutes(event.start_time)){toast('End time must be after start time.','error');return;}try{const saved=await db.saveEvent(meeting.id,event);if(id){Object.assign(findEvent(id),saved);}else{meeting.events=meeting.events||[];meeting.events.push(saved);}$('#eventDialog').close();renderPlanning();toast('Activity saved.','success');}catch(err){toast(err.message,'error');}}
async function deleteEvent(){const id=$('#eventId').value;if(!id||!confirm('Delete this scheduled activity?'))return;try{await db.deleteEvent(id);const m=selectedMeeting();m.events=m.events.filter(e=>e.id!==id);$('#eventDialog').close();renderPlanning();toast('Activity deleted.');}catch(err){toast(err.message,'error');}}
async function openMeetingTemplates(){
  const m=selectedMeeting();if(!m)return;
  try{
    const templates=await db.getMeetingTemplates(state.planning.schedule.unit_id,state.planning.schedule.program_type);
    $('#templateList').innerHTML=templates.length?templates.map(t=>`<div class="library-item"><div class="library-item-info"><div class="library-item-title">${esc(t.name)}</div><div class="library-item-meta">${esc(fmtTime(t.start_time))}–${esc(fmtTime(t.end_time))} • ${(t.events||t.meeting_template_events||[]).length} activities</div></div><button class="button secondary small apply-template" data-id="${t.id}">Apply</button></div>`).join(''):'<div class="muted-text">No templates have been saved for this unit and schedule type.</div>';
    $$('.apply-template').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Replace the selected meeting theme, times, and activities with this template?'))return;try{await db.applyMeetingTemplate(m.id,b.dataset.id);$('#templateDialog').close();await reloadPlanningPreserve(m.id);toast('Meeting template applied.','success');}catch(err){toast(err.message,'error');}}));
    $('#newTemplateName').value='';$('#templateDialog').showModal();
  }catch(err){toast(err.message,'error');}
}
async function saveCurrentMeetingTemplate(){const m=selectedMeeting(),name=$('#newTemplateName').value.trim();if(!m||!name){toast('Enter a template name.','error');return;}try{await db.saveMeetingAsTemplate(m.id,name);toast('Meeting template saved.','success');openMeetingTemplates();}catch(err){toast(err.message,'error');}}

function openActivityLibrary(){const list=state.planLookup.activityLibrary||[];$('#activityLibraryList').innerHTML=list.map(a=>`<div class="library-item"><div class="library-item-info"><div class="library-item-title">${esc(a.title)}</div><div class="library-item-meta">${esc(lookupName(state.planLookup.categories,a.category_id)||'Other')} • ${a.default_duration_minutes||30} minutes • ${esc(a.scope==='statewide'?'Statewide library':'Unit library')}</div></div><button class="button secondary small use-library" data-id="${a.id}">Use</button></div>`).join('')||'<div class="muted-text">No saved activities.</div>';$$('.use-library').forEach(b=>b.addEventListener('click',()=>{const a=list.find(x=>x.id===b.dataset.id);$('#libraryDialog').close();openEventDialog(null,a);}));$('#libraryDialog').showModal();}

async function renderSpecialActivities(){const unit=$('#activityUnitFilter').value||'all',range=$('#activityRangeFilter').value||'upcoming';try{const rows=await db.getSpecialActivities(unit,range);const now=new Date();let filtered=rows;if(range==='90'){const end=new Date();end.setDate(end.getDate()+90);filtered=rows.filter(x=>new Date(x.starts_at)<=end);}else if(range==='year'){filtered=rows.filter(x=>new Date(x.starts_at).getFullYear()===now.getFullYear());}else if(range==='history'){filtered=rows.filter(x=>new Date(x.ends_at)<now).reverse();}else filtered=rows.filter(x=>new Date(x.ends_at)>=now);$('#specialActivitiesList').innerHTML=filtered.length?filtered.map(a=>specialActivityCard(a)).join(''):`<div class="empty-state"><h2>No activities found</h2><p>No statewide special activities match this filter.</p></div>`;}catch(err){$('#specialActivitiesList').innerHTML=`<div class="empty-state"><h2>Unable to load activities</h2><p>${esc(err.message)}</p></div>`;}}
function specialActivityCard(a){const start=new Date(a.starts_at),end=new Date(a.ends_at);const editable=state.user&&(db.canEdit(a.unit_id,'cadet')||db.canEdit(a.unit_id,'senior'));return `<article class="activity-card"><div class="activity-card-unit">${esc(a.units?.name||unitName(a.unit_id))}</div><h3>${esc(a.title)}</h3><div class="activity-card-meta"><div><strong>When:</strong> ${esc(start.toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))} – ${esc(end.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))}</div>${a.location?`<div><strong>Where:</strong> ${esc(a.location)}</div>`:''}${a.audience?`<div><strong>Who:</strong> ${esc(a.audience)}</div>`:''}</div>${a.description?`<div class="activity-card-description">${esc(a.description)}</div>`:''}${editable?`<div class="activity-card-actions"><button class="button secondary small edit-special" data-id="${a.id}">Edit</button></div>`:''}</article>`;}
function openSpecialActivityDialog(existing=null){populateSpecialUnitSelector();$('#specialActivityId').value=existing?.id||'';if(existing?.unit_id)$('#specialUnit').value=existing.unit_id;$('#specialAudience').value=existing?.audience||'';$('#specialTitle').value=existing?.title||'';$('#specialLocation').value=existing?.location||'';$('#specialDescription').value=existing?.description||'';const base=new Date();base.setMinutes(Math.ceil(base.getMinutes()/15)*15,0,0);const end=new Date(base.getTime()+2*3600000);$('#specialStart').value=toLocalInput(existing?new Date(existing.starts_at):base);$('#specialEnd').value=toLocalInput(existing?new Date(existing.ends_at):end);$('#specialPublish').checked=existing?existing.status==='published':true;$('#specialActivityDialog').showModal();}
function toLocalInput(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
async function saveSpecialActivity(e){e.preventDefault();const data={id:$('#specialActivityId').value||null,unit_id:$('#specialUnit').value,title:$('#specialTitle').value.trim(),audience:$('#specialAudience').value.trim(),starts_at:new Date($('#specialStart').value).toISOString(),ends_at:new Date($('#specialEnd').value).toISOString(),location:$('#specialLocation').value.trim(),description:$('#specialDescription').value.trim(),status:$('#specialPublish').checked?'published':'draft'};try{await db.saveSpecialActivity(data);$('#specialActivityDialog').close();renderSpecialActivities();toast('Special activity saved.','success');}catch(err){toast(err.message,'error');}}

async function renderAdmin(){if(!isAdminAny())return;activateAdminPage(state.activeAdminPage||'units');}
function activateAdminPage(page){state.activeAdminPage=page;$$('.admin-nav-item').forEach(x=>x.classList.toggle('active',x.dataset.adminPage===page));$$('.admin-page').forEach(x=>x.classList.remove('active'));$(`#admin${page[0].toUpperCase()+page.slice(1)}Page`)?.classList.add('active');({units:renderAdminUnits,users:renderAdminUsers,rooms:renderAdminRooms,settings:renderAdminSettings,requirements:renderAdminRequirements,audit:renderAdminAudit}[page]||(()=>{}))();}
async function renderAdminUnits(){const el=$('#adminUnitsPage');const units=adminUnits();el.innerHTML=`<div class="admin-actions"><div><h2>Units</h2><div class="muted-text">App Administrators can create units. Unit Administrators can view their assigned unit.</div></div>${state.user?.isAppAdmin?'<button id="adminAddUnit" class="button primary">+ Add Unit</button>':''}</div><table class="admin-table"><thead><tr><th>Charter</th><th>Unit</th><th>Normal Meeting</th><th>Hours</th><th></th></tr></thead><tbody>${units.map(u=>`<tr><td>${esc(u.charter_number||'')}</td><td><strong>${esc(u.name)}</strong><div class="muted-text">${esc([u.city,u.state].filter(Boolean).join(', '))}</div></td><td>${esc(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][u.meeting_weekday]||'')}</td><td>${esc(fmtTime(u.default_start_time))}–${esc(fmtTime(u.default_end_time))}</td><td>${state.user?.isAppAdmin?`<button class="button secondary small edit-unit" data-id="${u.id}">Edit</button>`:''}</td></tr>`).join('')}</tbody></table><div id="unitEditor"></div>`;$('#adminAddUnit')?.addEventListener('click',()=>renderUnitEditor());$$('.edit-unit').forEach(b=>b.addEventListener('click',()=>renderUnitEditor(units.find(u=>u.id===b.dataset.id))));}
function renderUnitEditor(u=null){const el=$('#unitEditor');el.innerHTML=`<div class="card" style="margin-top:16px"><h3>${u?'Edit':'Add'} Unit</h3><form id="unitEditorForm" class="form-grid two-col"><input type="hidden" id="auId" value="${esc(u?.id||'')}"><div class="field"><label>Charter Number</label><input id="auCharter" value="${esc(u?.charter_number||'')}" required></div><div class="field"><label>Unit Name</label><input id="auName" value="${esc(u?.name||'')}" required></div><div class="field"><label>City</label><input id="auCity" value="${esc(u?.city||'')}"></div><div class="field"><label>State</label><input id="auState" value="${esc(u?.state||'MT')}"></div><div class="field"><label>Normal Meeting Day</label><select id="auWeekday">${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((x,i)=>`<option value="${i}" ${Number(u?.meeting_weekday??1)===i?'selected':''}>${x}</option>`).join('')}</select></div><div></div><div class="field"><label>Start</label><input id="auStart" type="time" value="${String(u?.default_start_time||'18:30').slice(0,5)}"></div><div class="field"><label>End</label><input id="auEnd" type="time" value="${String(u?.default_end_time||'21:00').slice(0,5)}"></div><div class="span-2"><button class="button primary">Save Unit</button></div></form></div>`;$('#unitEditorForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.adminSaveUnit({id:$('#auId').value||null,charter_number:$('#auCharter').value.trim(),name:$('#auName').value.trim(),city:$('#auCity').value.trim(),state:$('#auState').value.trim(),meeting_weekday:Number($('#auWeekday').value),default_start_time:$('#auStart').value,default_end_time:$('#auEnd').value,active:true});state.units=await db.getUnits();populateUnitSelectors();renderAdminUnits();toast('Unit saved.','success');}catch(err){toast(err.message,'error');}});}
async function renderAdminRooms(){const el=$('#adminRoomsPage'),units=adminUnits();const unitId=el.dataset.unitId&&units.some(u=>u.id===el.dataset.unitId)?el.dataset.unitId:units[0]?.id;if(!unitId){el.innerHTML='<p>No administrable units.</p>';return;}const look=await db.getLookupData(unitId);el.innerHTML=`<div class="admin-actions"><div><h2>Rooms & Locations</h2><div class="muted-text">Reusable room columns for weekly meeting planning.</div></div><select id="adminRoomUnit">${units.map(u=>`<option value="${u.id}" ${u.id===unitId?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><div class="settings-grid">${look.rooms.map(r=>`<div class="card"><strong>${esc(r.name)}</strong><div class="muted-text">Sort order ${r.sort_order}</div></div>`).join('')}<form id="addRoomForm" class="card"><strong>Add Room</strong><div class="field" style="margin-top:8px"><label>Name</label><input id="newRoomName" required></div><button class="button primary small" style="margin-top:8px">Add</button></form></div>`;$('#adminRoomUnit').addEventListener('change',e=>{el.dataset.unitId=e.target.value;renderAdminRooms();});$('#addRoomForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.adminSaveRoom({unit_id:unitId,name:$('#newRoomName').value.trim(),sort_order:look.rooms.length+1,active:true});renderAdminRooms();toast('Room added.','success');}catch(err){toast(err.message,'error');}});}
async function renderAdminUsers(){const el=$('#adminUsersPage'),units=adminUnits();const unitId=el.dataset.unitId&&units.some(u=>u.id===el.dataset.unitId)?el.dataset.unitId:units[0]?.id;if(!unitId){el.innerHTML='<p>No administrable units.</p>';return;}try{const users=await db.adminListUsers(unitId);el.innerHTML=`<div class="admin-actions"><div><h2>Users & Permissions</h2><div class="muted-text">Unit Admins can grant cadet/senior editing for their units. App Admins can manage all units and App Administrators.</div></div><select id="adminUserUnit">${units.map(u=>`<option value="${u.id}" ${u.id===unitId?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><table class="admin-table"><thead><tr><th>User</th><th>Cadet</th><th>Senior</th><th>Unit Admin</th><th>App Admin</th></tr></thead><tbody>${users.map(u=>{const p=(u.permissions||[]).find(x=>x.unit_id===unitId)||{};return `<tr><td><strong>${esc(u.display_name||u.email)}</strong><div class="muted-text">${esc(u.email||'')}</div></td><td>${p.can_edit_cadet?'✓':''}</td><td>${p.can_edit_senior?'✓':''}</td><td>${p.is_unit_admin?'✓':''}</td><td>${u.is_app_admin?'✓':''}</td></tr>`;}).join('')}</tbody></table><div class="card" style="margin-top:16px"><h3>Invite / Update User</h3><form id="adminUserForm" class="form-grid two-col"><div class="field"><label>Email</label><input id="admEmail" type="email" required></div><div class="field"><label>Display Name</label><input id="admName"></div><div class="field"><label class="check-label"><input type="checkbox" id="admCadet"> Edit Cadet Schedule</label></div><div class="field"><label class="check-label"><input type="checkbox" id="admSenior"> Edit Senior Schedule</label></div>${state.user?.isAppAdmin?`<div class="field"><label class="check-label"><input type="checkbox" id="admUnitAdmin"> Unit Administrator</label></div><div class="field"><label class="check-label"><input type="checkbox" id="admAppAdmin"> App Administrator</label></div>`:''}<div class="span-2"><button class="button primary">Invite / Save User</button></div></form></div>`;$('#adminUserUnit').addEventListener('change',e=>{el.dataset.unitId=e.target.value;renderAdminUsers();});$('#adminUserForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.adminUpsertUser({action:'upsert',email:$('#admEmail').value.trim(),display_name:$('#admName').value.trim(),unit_id:unitId,can_edit_cadet:$('#admCadet').checked,can_edit_senior:$('#admSenior').checked,is_unit_admin:$('#admUnitAdmin')?.checked||false,is_app_admin:$('#admAppAdmin')?.checked||false});toast('User invitation/permissions saved.','success');renderAdminUsers();}catch(err){toast(err.message,'error');}});}catch(err){el.innerHTML=`<h2>Users & Permissions</h2><div class="empty-state"><p>${esc(err.message)}</p></div>`;}}
async function renderAdminSettings(){const el=$('#adminSettingsPage'),units=adminUnits();const unitId=el.dataset.unitId&&units.some(u=>u.id===el.dataset.unitId)?el.dataset.unitId:units[0]?.id;if(!unitId){el.innerHTML='<p>No administrable units.</p>';return;}const look=await db.getLookupData(unitId);el.innerHTML=`<div class="admin-actions"><div><h2>Schedule Settings</h2><div class="muted-text">Themes, uniforms, and activity-library entries can be statewide defaults or unit-specific.</div></div><select id="adminSettingsUnit">${units.map(u=>`<option value="${u.id}" ${u.id===unitId?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><div class="settings-grid"><div class="card"><h3>Meeting Themes</h3>${look.themes.map(x=>`<div>${esc(x.name)}</div>`).join('')}<form id="addThemeForm" class="field" style="margin-top:10px"><label>Add Unit Theme</label><input id="newTheme" required><button class="button secondary small">Add Theme</button></form></div><div class="card"><h3>Uniforms</h3>${look.uniforms.map(x=>`<div>${esc(x.name)}</div>`).join('')}<form id="addUniformForm" class="field" style="margin-top:10px"><label>Add Unit Uniform</label><input id="newUniform" required><button class="button secondary small">Add Uniform</button></form></div><div class="card"><h3>Activity Library</h3>${look.activityLibrary.slice(0,12).map(x=>`<div>${esc(x.title)} <span class="muted-text">(${x.default_duration_minutes||30} min)</span></div>`).join('')}<form id="addLibraryForm" class="form-grid" style="margin-top:10px"><div class="field"><label>Activity</label><input id="newLibTitle" required></div><div class="field"><label>Default Minutes</label><input id="newLibMinutes" type="number" min="5" step="5" value="30"></div><button class="button secondary small">Add Unit Activity</button></form></div></div>`;$('#adminSettingsUnit').addEventListener('change',e=>{el.dataset.unitId=e.target.value;renderAdminSettings();});$('#addThemeForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.adminAddTheme(unitId,$('#newTheme').value.trim());renderAdminSettings();}catch(err){toast(err.message,'error');}});$('#addUniformForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.adminAddUniform(unitId,$('#newUniform').value.trim());renderAdminSettings();}catch(err){toast(err.message,'error');}});$('#addLibraryForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.adminAddLibraryActivity(unitId,$('#newLibTitle').value.trim(),Number($('#newLibMinutes').value));renderAdminSettings();}catch(err){toast(err.message,'error');}});}
async function renderAdminRequirements(){const el=$('#adminRequirementsPage');if(!state.user?.isAppAdmin){el.innerHTML='';return;}const unitId=state.units[0]?.id;const look=unitId?await db.getLookupData(unitId):{requirements:[],categories:[]};el.innerHTML=`<h2>CAP Monthly Content Requirements</h2><p class="muted-text">These values drive the live planning dashboard. Update them here if CAP requirements change; no code modification is needed.</p><table class="admin-table"><thead><tr><th>Requirement</th><th>Category</th><th>Minimum Minutes</th><th>Occurrence Only</th><th></th></tr></thead><tbody>${look.requirements.map(r=>`<tr data-req-id="${r.id}"><td><strong>${esc(r.name)}</strong></td><td>${esc(lookupName(look.categories,r.category_id))}</td><td><input class="req-min" type="number" min="0" step="5" value="${r.minimum_minutes??''}" style="width:90px"></td><td><input class="req-occ" type="checkbox" ${r.occurrence_required?'checked':''}></td><td><button class="button secondary small save-req">Save</button></td></tr>`).join('')}</tbody></table>`;$$('.save-req').forEach(b=>b.addEventListener('click',async()=>{const tr=b.closest('tr'),id=tr.dataset.reqId,occ=tr.querySelector('.req-occ').checked,val=tr.querySelector('.req-min').value;try{await db.adminUpdateRequirement(id,{minimum_minutes:occ?null:(val===''?null:Number(val)),occurrence_required:occ});toast('Requirement updated.','success');renderAdminRequirements();}catch(err){toast(err.message,'error');}}));}
async function renderAdminAudit(){const el=$('#adminAuditPage');if(!state.user?.isAppAdmin){el.innerHTML='';return;}try{const rows=await db.adminGetAudit();el.innerHTML=`<h2>Audit Log</h2><p class="muted-text">Recent changes retained for accountability and schedule-history troubleshooting.</p><table class="admin-table"><thead><tr><th>When</th><th>User</th><th>Action</th><th>Table</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(new Date(r.created_at).toLocaleString())}</td><td>${esc(r.profiles?.display_name||r.actor_user_id||'System')}</td><td>${esc(r.action)}</td><td>${esc(r.table_name)}</td></tr>`).join('')}</tbody></table>`;}catch(err){el.innerHTML=`<h2>Audit Log</h2><p>${esc(err.message)}</p>`;}}

document.addEventListener('click',e=>{const b=e.target.closest('.edit-special');if(b){db.getSpecialActivities('all','history').then(rows=>{const a=rows.find(x=>x.id===b.dataset.id);if(a)openSpecialActivityDialog(a);});}});

init().catch(err=>{console.error(err);toast(`Startup error: ${err.message}`,'error');$('#modeBadge').textContent='Startup Error';$('#modeBadge').className='badge danger';});
