-- Mirrors live Supabase migration 20261005051208: uniform_inspections_shared_module
-- Schema only. Production data migration is intentionally NOT committed.

alter table public.members
  add column if not exists current_grade text;

create table if not exists public.uniform_global_permissions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_app_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.uniform_unit_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  unit_id uuid not null references public.units(id) on delete cascade,
  can_inspect boolean not null default false,
  is_unit_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, unit_id)
);

create table if not exists public.uniform_grading_rules (
  grade_group text primary key check (grade_group in ('airman','nco_officer')),
  passing_min smallint not null check (passing_min between 0 and 10),
  excellent_min smallint not null check (excellent_min between 0 and 10),
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null
);

create table if not exists public.uniform_inspections (
  id bigint generated by default as identity primary key,
  legacy_inspection_id bigint unique,
  member_id uuid not null references public.members(id) on delete restrict,
  unit_id uuid null references public.units(id) on delete restrict,
  inspection_date date not null default current_date,
  grade_at_inspection text not null,
  grade_group text not null check (grade_group in ('airman','nco_officer')),
  personal_appearance smallint not null check (personal_appearance between 0 and 2),
  garments smallint not null check (garments between 0 and 2),
  accoutrements smallint not null check (accoutrements between 0 and 2),
  footwear smallint not null check (footwear between 0 and 2),
  military_bearing smallint not null check (military_bearing between 0 and 2),
  total_score smallint not null check (total_score between 0 and 10),
  overall_rating text not null check (overall_rating in ('Needs Improvement','Satisfactory','Excellent')),
  passed boolean not null,
  notes text,
  evaluator_user_id uuid null references auth.users(id) on delete set null,
  evaluator_name text not null,
  legacy_evaluator_id uuid,
  client_uuid uuid unique,
  created_at timestamptz not null default now()
);

create index if not exists idx_uniform_inspections_member_date
  on public.uniform_inspections(member_id, inspection_date desc);
create index if not exists idx_uniform_inspections_unit_date
  on public.uniform_inspections(unit_id, inspection_date desc);
create index if not exists idx_uniform_inspections_evaluator
  on public.uniform_inspections(evaluator_user_id);

create or replace function public.is_uniform_app_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select exists (
    select 1 from public.uniform_global_permissions p
    where p.user_id = auth.uid() and p.is_app_admin
  );
$$;

create or replace function public.has_uniform_unit_access(p_unit_id uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select public.is_uniform_app_admin()
     or exists (
       select 1 from public.uniform_unit_permissions p
       where p.user_id = auth.uid()
         and p.unit_id = p_unit_id
         and (p.can_inspect or p.is_unit_admin)
     );
$$;

create or replace function public.has_uniform_unit_admin(p_unit_id uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select public.is_uniform_app_admin()
     or exists (
       select 1 from public.uniform_unit_permissions p
       where p.user_id = auth.uid()
         and p.unit_id = p_unit_id
         and p.is_unit_admin
     );
$$;

create or replace function public.has_uniform_any_access()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select public.is_uniform_app_admin()
     or exists (
       select 1 from public.uniform_unit_permissions p
       where p.user_id = auth.uid()
         and (p.can_inspect or p.is_unit_admin)
     );
$$;

create or replace function public.can_read_uniform_member(p_member_id uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select public.is_uniform_app_admin()
     or exists (
       select 1
       from public.member_unit_assignments a
       join public.uniform_unit_permissions p
         on p.unit_id = a.unit_id
        and p.user_id = auth.uid()
        and (p.can_inspect or p.is_unit_admin)
       where a.member_id = p_member_id and a.active
     )
     or exists (
       select 1 from public.uniform_inspections i
       where i.member_id = p_member_id and i.evaluator_user_id = auth.uid()
     );
$$;

drop policy if exists uniform_members_read on public.members;
create policy uniform_members_read on public.members for select to authenticated
using (public.can_read_uniform_member(id));

drop policy if exists uniform_member_assignments_read on public.member_unit_assignments;
create policy uniform_member_assignments_read on public.member_unit_assignments for select to authenticated
using (public.can_read_uniform_member(member_id));

alter table public.uniform_global_permissions enable row level security;
alter table public.uniform_unit_permissions enable row level security;
alter table public.uniform_grading_rules enable row level security;
alter table public.uniform_inspections enable row level security;

drop policy if exists uniform_global_permissions_self_read on public.uniform_global_permissions;
create policy uniform_global_permissions_self_read
on public.uniform_global_permissions for select to authenticated
using (user_id = auth.uid() or public.is_uniform_app_admin());

drop policy if exists uniform_unit_permissions_self_read on public.uniform_unit_permissions;
create policy uniform_unit_permissions_self_read
on public.uniform_unit_permissions for select to authenticated
using (user_id = auth.uid() or public.is_uniform_app_admin());

drop policy if exists uniform_grading_rules_read on public.uniform_grading_rules;
create policy uniform_grading_rules_read
on public.uniform_grading_rules for select to authenticated
using (public.has_uniform_any_access());

drop policy if exists uniform_grading_rules_admin_insert on public.uniform_grading_rules;
create policy uniform_grading_rules_admin_insert
on public.uniform_grading_rules for insert to authenticated
with check (public.is_uniform_app_admin());

drop policy if exists uniform_grading_rules_admin_update on public.uniform_grading_rules;
create policy uniform_grading_rules_admin_update
on public.uniform_grading_rules for update to authenticated
using (public.is_uniform_app_admin())
with check (public.is_uniform_app_admin());

drop policy if exists uniform_inspections_read on public.uniform_inspections;
create policy uniform_inspections_read
on public.uniform_inspections for select to authenticated
using (
  public.is_uniform_app_admin()
  or evaluator_user_id = auth.uid()
  or (unit_id is not null and public.has_uniform_unit_access(unit_id))
);

drop policy if exists uniform_inspections_admin_delete on public.uniform_inspections;
create policy uniform_inspections_admin_delete
on public.uniform_inspections for delete to authenticated
using (
  public.is_uniform_app_admin()
  or (unit_id is not null and public.has_uniform_unit_admin(unit_id))
);

create or replace function public.uniform_calculate_inspection_result()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
declare
  score_total smallint;
  pass_min smallint;
  excellent_minimum smallint;
begin
  score_total := new.personal_appearance + new.garments + new.accoutrements + new.footwear + new.military_bearing;
  new.total_score := score_total;

  select r.passing_min, r.excellent_min
    into pass_min, excellent_minimum
  from public.uniform_grading_rules r
  where r.grade_group = new.grade_group;

  if pass_min is null or excellent_minimum is null then
    if new.grade_group = 'airman' then
      pass_min := 4;
      excellent_minimum := 6;
    else
      pass_min := 5;
      excellent_minimum := 8;
    end if;
  end if;

  if score_total < pass_min then
    new.overall_rating := 'Needs Improvement';
    new.passed := false;
  elsif score_total < excellent_minimum then
    new.overall_rating := 'Satisfactory';
    new.passed := true;
  else
    new.overall_rating := 'Excellent';
    new.passed := true;
  end if;
  return new;
end;
$$;

drop trigger if exists uniform_inspections_calculate_result on public.uniform_inspections;
create trigger uniform_inspections_calculate_result
before insert or update of personal_appearance, garments, accoutrements, footwear, military_bearing, grade_group
on public.uniform_inspections
for each row execute function public.uniform_calculate_inspection_result();

create or replace view public.uniform_cadets
with (security_invoker = true)
as
select
  m.id,
  m.capid,
  m.first_name,
  m.last_name,
  trim(concat_ws(' ',m.first_name,m.last_name)) as name,
  m.current_grade as grade,
  (
    select a.unit_id
    from public.member_unit_assignments a
    where a.member_id = m.id and a.active and a.is_primary
    order by a.start_date desc, a.created_at desc
    limit 1
  ) as current_unit_id
from public.members m
where m.member_type = 'Cadet' and m.active;

create or replace function public.uniform_my_profile()
returns table (id uuid,email text,display_name text,role text,created_at timestamptz)
language sql stable security definer set search_path = pg_catalog
as $$
  select u.id,u.email::text,coalesce(p.display_name,u.email)::text,
         case when public.is_uniform_app_admin() then 'admin' else 'inspector' end::text,
         u.created_at
  from auth.users u
  left join public.profiles p on p.id=u.id
  where u.id=auth.uid() and public.has_uniform_any_access();
$$;

create or replace function public.uniform_list_units()
returns table (id uuid,charter_number text,name text,active boolean)
language sql stable security definer set search_path = pg_catalog
as $$
  select u.id,u.charter_number,u.name,u.active
  from public.units u
  where public.is_uniform_app_admin()
     or exists (
       select 1 from public.uniform_unit_permissions p
       where p.user_id=auth.uid() and p.unit_id=u.id and (p.can_inspect or p.is_unit_admin)
     )
  order by u.charter_number nulls last,u.name;
$$;

create or replace function public.uniform_list_inspectors()
returns table (id uuid,display_name text)
language sql stable security definer set search_path = pg_catalog
as $$
  select distinct u.id,coalesce(p.display_name,u.email)::text
  from auth.users u
  left join public.profiles p on p.id=u.id
  where public.has_uniform_any_access()
    and (
      exists (select 1 from public.uniform_global_permissions g where g.user_id=u.id and g.is_app_admin)
      or exists (select 1 from public.uniform_unit_permissions up where up.user_id=u.id and (up.can_inspect or up.is_unit_admin))
    )
  order by 2;
$$;

create or replace function public.uniform_list_users()
returns table (id uuid,email text,display_name text,role text,created_at timestamptz)
language sql stable security definer set search_path = pg_catalog
as $$
  select u.id,u.email::text,coalesce(p.display_name,u.email)::text,
         case when exists (select 1 from public.uniform_global_permissions g where g.user_id=u.id and g.is_app_admin)
              then 'admin' else 'inspector' end::text,
         u.created_at
  from auth.users u
  left join public.profiles p on p.id=u.id
  where public.is_uniform_app_admin()
    and (
      exists (select 1 from public.uniform_global_permissions g where g.user_id=u.id and g.is_app_admin)
      or exists (select 1 from public.uniform_unit_permissions up where up.user_id=u.id and (up.can_inspect or up.is_unit_admin))
    )
  order by display_name;
$$;

create or replace function public.uniform_upsert_cadet(
  p_capid text,p_first_name text,p_last_name text,p_grade text,p_unit_id uuid
)
returns table (id uuid,capid text,first_name text,last_name text,name text,grade text,current_unit_id uuid)
language plpgsql security definer set search_path = pg_catalog
as $$
declare
  v_member_id uuid;
  v_current_unit uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  if p_unit_id is null or not public.has_uniform_unit_access(p_unit_id) then
    raise exception 'You do not have Uniform Inspection access to this unit.';
  end if;
  if nullif(trim(p_capid),'') is null then raise exception 'CAPID is required.'; end if;

  insert into public.members(capid,first_name,last_name,member_type,active,current_grade,created_at,updated_at)
  values(trim(p_capid),trim(coalesce(p_first_name,'')),trim(coalesce(p_last_name,'')),'Cadet',true,nullif(trim(coalesce(p_grade,'')),''),now(),now())
  on conflict(capid) do update set
    first_name=excluded.first_name,last_name=excluded.last_name,
    current_grade=coalesce(excluded.current_grade,public.members.current_grade),
    active=true,updated_at=now()
  returning public.members.id into v_member_id;

  select a.unit_id into v_current_unit
  from public.member_unit_assignments a
  where a.member_id=v_member_id and a.active and a.is_primary
  limit 1;

  if v_current_unit is null then
    insert into public.member_unit_assignments(member_id,unit_id,is_primary,active,start_date)
    values(v_member_id,p_unit_id,true,true,current_date);
  elsif v_current_unit <> p_unit_id and public.is_uniform_app_admin() then
    update public.member_unit_assignments
      set active=false,is_primary=false,end_date=coalesce(end_date,current_date),updated_at=now()
    where member_id=v_member_id and active and is_primary;
    insert into public.member_unit_assignments(member_id,unit_id,is_primary,active,start_date)
    values(v_member_id,p_unit_id,true,true,current_date);
  end if;

  return query select c.id,c.capid,c.first_name,c.last_name,c.name,c.grade,c.current_unit_id
  from public.uniform_cadets c where c.id=v_member_id;
end;
$$;

create or replace function public.uniform_save_inspection(p_payload jsonb)
returns jsonb
language plpgsql security definer set search_path = pg_catalog
as $$
declare
  v_uid uuid := auth.uid();
  v_unit uuid;
  v_member record;
  v_inspection public.uniform_inspections%rowtype;
  v_evaluator_name text;
  v_client_uuid uuid;
begin
  if v_uid is null then raise exception 'Authentication required.'; end if;
  v_unit := nullif(p_payload->>'unit_id','')::uuid;
  if v_unit is null or not public.has_uniform_unit_access(v_unit) then
    raise exception 'You do not have Uniform Inspection access to this unit.';
  end if;

  select * into v_member
  from public.uniform_upsert_cadet(
    p_payload->>'capid',p_payload->>'first_name',p_payload->>'last_name',
    p_payload->>'grade',v_unit
  ) limit 1;

  select coalesce(p.display_name,u.email)::text into v_evaluator_name
  from auth.users u left join public.profiles p on p.id=u.id where u.id=v_uid;
  v_client_uuid := nullif(p_payload->>'client_uuid','')::uuid;

  insert into public.uniform_inspections(
    member_id,unit_id,inspection_date,grade_at_inspection,grade_group,
    personal_appearance,garments,accoutrements,footwear,military_bearing,
    total_score,overall_rating,passed,notes,evaluator_user_id,evaluator_name,client_uuid
  ) values (
    v_member.id,v_unit,coalesce(nullif(p_payload->>'inspection_date','')::date,current_date),
    coalesce(nullif(p_payload->>'grade_at_inspection',''),v_member.grade,''),
    p_payload->>'grade_group',
    (p_payload->>'personal_appearance')::smallint,(p_payload->>'garments')::smallint,
    (p_payload->>'accoutrements')::smallint,(p_payload->>'footwear')::smallint,
    (p_payload->>'military_bearing')::smallint,
    0,'Needs Improvement',false,nullif(p_payload->>'notes',''),
    v_uid,coalesce(v_evaluator_name,'Unknown Inspector'),v_client_uuid
  )
  on conflict(client_uuid) do update set
    member_id=excluded.member_id,unit_id=excluded.unit_id,inspection_date=excluded.inspection_date,
    grade_at_inspection=excluded.grade_at_inspection,grade_group=excluded.grade_group,
    personal_appearance=excluded.personal_appearance,garments=excluded.garments,
    accoutrements=excluded.accoutrements,footwear=excluded.footwear,
    military_bearing=excluded.military_bearing,notes=excluded.notes,
    evaluator_user_id=excluded.evaluator_user_id,evaluator_name=excluded.evaluator_name
  returning * into v_inspection;

  return jsonb_build_object(
    'inspection',
    to_jsonb(v_inspection) || jsonb_build_object(
      'cadets',jsonb_build_object(
        'id',v_member.id,'capid',v_member.capid,'first_name',v_member.first_name,
        'last_name',v_member.last_name,'name',v_member.name,'grade',v_member.grade,
        'current_unit_id',v_member.current_unit_id
      ),
      'units',(select to_jsonb(u) from (select id,charter_number,name,active from public.units where id=v_unit) u)
    ),
    'cadet',to_jsonb(v_member)
  );
end;
$$;

revoke all on table public.uniform_global_permissions from anon;
revoke all on table public.uniform_unit_permissions from anon;
revoke all on table public.uniform_grading_rules from anon;
revoke all on table public.uniform_inspections from anon;
revoke all on table public.uniform_cadets from anon;

grant select on public.uniform_global_permissions to authenticated;
grant select on public.uniform_unit_permissions to authenticated;
grant select,insert,update on public.uniform_grading_rules to authenticated;
grant select,delete on public.uniform_inspections to authenticated;
grant select on public.uniform_cadets to authenticated;

revoke execute on function public.is_uniform_app_admin() from public,anon;
revoke execute on function public.has_uniform_unit_access(uuid) from public,anon;
revoke execute on function public.has_uniform_unit_admin(uuid) from public,anon;
revoke execute on function public.has_uniform_any_access() from public,anon;
revoke execute on function public.can_read_uniform_member(uuid) from public,anon;
revoke execute on function public.uniform_my_profile() from public,anon;
revoke execute on function public.uniform_list_units() from public,anon;
revoke execute on function public.uniform_list_inspectors() from public,anon;
revoke execute on function public.uniform_list_users() from public,anon;
revoke execute on function public.uniform_upsert_cadet(text,text,text,text,uuid) from public,anon;
revoke execute on function public.uniform_save_inspection(jsonb) from public,anon;

grant execute on function public.is_uniform_app_admin() to authenticated;
grant execute on function public.has_uniform_unit_access(uuid) to authenticated;
grant execute on function public.has_uniform_unit_admin(uuid) to authenticated;
grant execute on function public.has_uniform_any_access() to authenticated;
grant execute on function public.can_read_uniform_member(uuid) to authenticated;
grant execute on function public.uniform_my_profile() to authenticated;
grant execute on function public.uniform_list_units() to authenticated;
grant execute on function public.uniform_list_inspectors() to authenticated;
grant execute on function public.uniform_list_users() to authenticated;
grant execute on function public.uniform_upsert_cadet(text,text,text,text,uuid) to authenticated;
grant execute on function public.uniform_save_inspection(jsonb) to authenticated;
